// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: messages.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 统一的消息类型
type MessageType int32

const (
	MessageType_PASSWORD_REQUIRED MessageType = 0
	MessageType_AUTH_REQUEST      MessageType = 1
	MessageType_AUTH_RESPONSE     MessageType = 2
	MessageType_SERVICE_REQUEST   MessageType = 3
	MessageType_SERVICE_RESPONSE  MessageType = 4
	MessageType_SERVER_SHUTDOWN   MessageType = 5
	MessageType_CLIENT_SHUTDOWN   MessageType = 6
	MessageType_HEARTBEAT         MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "PASSWORD_REQUIRED",
		1: "AUTH_REQUEST",
		2: "AUTH_RESPONSE",
		3: "SERVICE_REQUEST",
		4: "SERVICE_RESPONSE",
		5: "SERVER_SHUTDOWN",
		6: "CLIENT_SHUTDOWN",
		7: "HEARTBEAT",
	}
	MessageType_value = map[string]int32{
		"PASSWORD_REQUIRED": 0,
		"AUTH_REQUEST":      1,
		"AUTH_RESPONSE":     2,
		"SERVICE_REQUEST":   3,
		"SERVICE_RESPONSE":  4,
		"SERVER_SHUTDOWN":   5,
		"CLIENT_SHUTDOWN":   6,
		"HEARTBEAT":         7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

// 错误代码枚举
type ErrorCode int32

const (
	ErrorCode_NO_ERROR                ErrorCode = 0
	ErrorCode_SERVICE_NOT_FOUND       ErrorCode = 1
	ErrorCode_PROTOCOL_NOT_SUPPORTED  ErrorCode = 2
	ErrorCode_SERVICE_DISABLED        ErrorCode = 3
	ErrorCode_INVALID_PASSWORD        ErrorCode = 4
	ErrorCode_PASSWORD_REQUIRED_ERROR ErrorCode = 5
	ErrorCode_AUTH_FAILED             ErrorCode = 6
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "NO_ERROR",
		1: "SERVICE_NOT_FOUND",
		2: "PROTOCOL_NOT_SUPPORTED",
		3: "SERVICE_DISABLED",
		4: "INVALID_PASSWORD",
		5: "PASSWORD_REQUIRED_ERROR",
		6: "AUTH_FAILED",
	}
	ErrorCode_value = map[string]int32{
		"NO_ERROR":                0,
		"SERVICE_NOT_FOUND":       1,
		"PROTOCOL_NOT_SUPPORTED":  2,
		"SERVICE_DISABLED":        3,
		"INVALID_PASSWORD":        4,
		"PASSWORD_REQUIRED_ERROR": 5,
		"AUTH_FAILED":             6,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

// 统一的消息结构
type UnifiedMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=p2pforward.MessageType" json:"type,omitempty"`
	// 认证相关字段
	Password        string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Success         bool   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	RequirePassword bool   `protobuf:"varint,4,opt,name=require_password,json=requirePassword,proto3" json:"require_password,omitempty"`
	// 服务请求相关字段
	ServiceName     string `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Protocol        string `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ServicePassword string `protobuf:"bytes,7,opt,name=service_password,json=servicePassword,proto3" json:"service_password,omitempty"`
	// 通用字段
	Message       string            `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     ErrorCode         `protobuf:"varint,9,opt,name=error_code,json=errorCode,proto3,enum=p2pforward.ErrorCode" json:"error_code,omitempty"`
	Data          map[string]string `protobuf:"bytes,10,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnifiedMessage) Reset() {
	*x = UnifiedMessage{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnifiedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnifiedMessage) ProtoMessage() {}

func (x *UnifiedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnifiedMessage.ProtoReflect.Descriptor instead.
func (*UnifiedMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *UnifiedMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_PASSWORD_REQUIRED
}

func (x *UnifiedMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UnifiedMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnifiedMessage) GetRequirePassword() bool {
	if x != nil {
		return x.RequirePassword
	}
	return false
}

func (x *UnifiedMessage) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *UnifiedMessage) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *UnifiedMessage) GetServicePassword() string {
	if x != nil {
		return x.ServicePassword
	}
	return ""
}

func (x *UnifiedMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UnifiedMessage) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_NO_ERROR
}

func (x *UnifiedMessage) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\n" +
	"p2pforward\"\xcb\x03\n" +
	"\x0eUnifiedMessage\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.p2pforward.MessageTypeR\x04type\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12)\n" +
	"\x10require_password\x18\x04 \x01(\bR\x0frequirePassword\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12)\n" +
	"\x10service_password\x18\a \x01(\tR\x0fservicePassword\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x124\n" +
	"\n" +
	"error_code\x18\t \x01(\x0e2\x15.p2pforward.ErrorCodeR\terrorCode\x128\n" +
	"\x04data\x18\n" +
	" \x03(\v2$.p2pforward.UnifiedMessage.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xad\x01\n" +
	"\vMessageType\x12\x15\n" +
	"\x11PASSWORD_REQUIRED\x10\x00\x12\x10\n" +
	"\fAUTH_REQUEST\x10\x01\x12\x11\n" +
	"\rAUTH_RESPONSE\x10\x02\x12\x13\n" +
	"\x0fSERVICE_REQUEST\x10\x03\x12\x14\n" +
	"\x10SERVICE_RESPONSE\x10\x04\x12\x13\n" +
	"\x0fSERVER_SHUTDOWN\x10\x05\x12\x13\n" +
	"\x0fCLIENT_SHUTDOWN\x10\x06\x12\r\n" +
	"\tHEARTBEAT\x10\a*\xa6\x01\n" +
	"\tErrorCode\x12\f\n" +
	"\bNO_ERROR\x10\x00\x12\x15\n" +
	"\x11SERVICE_NOT_FOUND\x10\x01\x12\x1a\n" +
	"\x16PROTOCOL_NOT_SUPPORTED\x10\x02\x12\x14\n" +
	"\x10SERVICE_DISABLED\x10\x03\x12\x14\n" +
	"\x10INVALID_PASSWORD\x10\x04\x12\x1b\n" +
	"\x17PASSWORD_REQUIRED_ERROR\x10\x05\x12\x0f\n" +
	"\vAUTH_FAILED\x10\x06B'Z%github.com/Hexrotor/f2p/protob\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_messages_proto_goTypes = []any{
	(MessageType)(0),       // 0: p2pforward.MessageType
	(ErrorCode)(0),         // 1: p2pforward.ErrorCode
	(*UnifiedMessage)(nil), // 2: p2pforward.UnifiedMessage
	nil,                    // 3: p2pforward.UnifiedMessage.DataEntry
}
var file_messages_proto_depIdxs = []int32{
	0, // 0: p2pforward.UnifiedMessage.type:type_name -> p2pforward.MessageType
	1, // 1: p2pforward.UnifiedMessage.error_code:type_name -> p2pforward.ErrorCode
	3, // 2: p2pforward.UnifiedMessage.data:type_name -> p2pforward.UnifiedMessage.DataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
